FROM python:3.7-alpine
COPY . /code
WORKDIR /code
ENV HTTP_PROXY "http://wwwproxy.unimelb.edu.au:8000"
ENV HTTPS_PROXY "http://wwwproxy.unimelb.edu.au:8000"
ENV NO_PROXY "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install -r requirements.txt

