# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVJZU_7LqsQMgc7FuDSqAWfHeEXfjiKp
"""

def main():
  print("Hello World!")
  
main()